#
# Docker compose
# Common configurations
#
version: '3.7'

services:
    # Apache web server
    web:
        image: httpd
        env_file: .env
        working_dir: /var/www/html
        volumes:
            - ./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./public:/var/www/html
        ports:
            - ${HTTP_PORT}:80
        networks:
            - frontproxynet
            - default

        # For traefik user
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_ID}.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_ID}.loadbalancer.server.port=80"
            - "traefik.http.services.${APP_ID}.loadbalancer.passhostheader=true"
            - "traefik.http.routers.${APP_ID}.entrypoints=http"
            - "traefik.http.routers.${APP_ID}.rule=Host(`${HOSTNAME}`)"
            - "traefik.http.routers.${APP_ID}.service=${APP_ID}"
networks:
    frontproxynet:
        external: true

    default:
